Fix race condition.

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -83,9 +83,15 @@ jobs:
       - name: Test coupled_laplace_problem
         run: |
           cd coupled_laplace_problem
-          (./coupled_laplace_problem 2>&1 & ./fancy_boundary_condition >fbc.log)
+          ./coupled_laplace_problem &
+          pid=$!
+          ./fancy_boundary_condition
+          wait "$pid"
           sed -i '2d' solution-10.vtk
-          numdiff solution-10.vtk test_data/reference-10.vtk || (echo "error_test=coupled_laplace_problem/" >> $GITHUB_ENV && exit 1)
+          numdiff solution-10.vtk test_data/reference-10.vtk || {
+            echo "error_test=coupled_laplace_problem/" >> $GITHUB_ENV
+            exit 1
+          }
 
       - name: Create issue about failure
         if: failure() && github.event_name == 'schedule'
